var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/tools/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__f7778fb8._.js")
R.c("server/chunks/ssr/_07720ad9._.js")
R.c("server/chunks/ssr/_9581ceae._.js")
R.c("server/chunks/ssr/[root-of-the-server]__abfae794._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_81959fb0._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_app_layout_tsx_cc8184fa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_tools_[id]_page_actions_ecae2f34.js")
R.m(33955)
module.exports=R.m(33955).exports
