// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/activate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activate">> = Specific
  const handler = {} as typeof import("../../src/app/activate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/admin/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/codes/[batchId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/codes/[batchId]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/codes/[batchId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/codes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/codes">> = Specific
  const handler = {} as typeof import("../../src/app/admin/codes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/credits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/credits">> = Specific
  const handler = {} as typeof import("../../src/app/admin/credits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/encryption/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/encryption">> = Specific
  const handler = {} as typeof import("../../src/app/admin/encryption/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/logs">> = Specific
  const handler = {} as typeof import("../../src/app/admin/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/memberships/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/memberships">> = Specific
  const handler = {} as typeof import("../../src/app/admin/memberships/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/mini-config/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/mini-config">> = Specific
  const handler = {} as typeof import("../../src/app/admin/mini-config/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/oauth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/oauth">> = Specific
  const handler = {} as typeof import("../../src/app/admin/oauth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tools">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/credits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/credits">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/credits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/oauth-proxy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/oauth-proxy">> = Specific
  const handler = {} as typeof import("../../src/app/oauth-proxy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/tools/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools">> = Specific
  const handler = {} as typeof import("../../src/app/tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/activate">> = Specific
  const handler = {} as typeof import("../../src/app/api/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/activation-codes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/activation-codes">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/activation-codes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/admin-ids/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/admin-ids">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/admin-ids/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/announcements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/announcements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/audit-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audit-logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/audit-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/categories">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/check">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/credits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/credits">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/credits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/encryption-key/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/encryption-key">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/encryption-key/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/init-demo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/init-demo">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/init-demo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/memberships/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/memberships">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/memberships/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/mini-config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/mini-config">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/mini-config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/oauth-config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/oauth-config">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/oauth-config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[id]/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]/password">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[id]/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/workflow-configs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/workflow-configs">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/workflow-configs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/announcements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/api/announcements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/audit-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit-logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/audit-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/coze/access-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coze/access-token">> = Specific
  const handler = {} as typeof import("../../src/app/api/coze/access-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/coze/oauth/authorize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coze/oauth/authorize">> = Specific
  const handler = {} as typeof import("../../src/app/api/coze/oauth/authorize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/coze/oauth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coze/oauth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/coze/oauth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/coze/oauth/disconnect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coze/oauth/disconnect">> = Specific
  const handler = {} as typeof import("../../src/app/api/coze/oauth/disconnect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/credits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/credits">> = Specific
  const handler = {} as typeof import("../../src/app/api/credits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/favorites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/favorites">> = Specific
  const handler = {} as typeof import("../../src/app/api/favorites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/mini/home-config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mini/home-config">> = Specific
  const handler = {} as typeof import("../../src/app/api/mini/home-config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/referral/link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referral/link">> = Specific
  const handler = {} as typeof import("../../src/app/api/referral/link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/referral/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referral/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/referral/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/supabase-config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/supabase-config">> = Specific
  const handler = {} as typeof import("../../src/app/api/supabase-config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tools/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tools/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tools/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tools/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tools">> = Specific
  const handler = {} as typeof import("../../src/app/api/tools/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload/image">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload/media">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/password">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/wechat/wxacode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wechat/wxacode">> = Specific
  const handler = {} as typeof import("../../src/app/api/wechat/wxacode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workflow/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workflow/list">> = Specific
  const handler = {} as typeof import("../../src/app/api/workflow/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workflow/refresh-url/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workflow/refresh-url">> = Specific
  const handler = {} as typeof import("../../src/app/api/workflow/refresh-url/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workflow/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workflow/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/workflow/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workflow/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workflow/stream">> = Specific
  const handler = {} as typeof import("../../src/app/api/workflow/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workflow/task/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workflow/task/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/workflow/task/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workflow/task/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workflow/task/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/workflow/task/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
